//! Entity generation for SeaORM models
//!
//! This module generates the main entity struct with SeaORM 2.0 dense format.

use super::column;
use super::oneof::{
    extract_oneofs, generate_flatten_fields, generate_json_fields, generate_tagged_fields,
    is_oneof_field, OneofStrategy,
};
use super::relation::generate_relation_fields;
use super::types::map_proto_type;
use heck::ToSnakeCase;
use proc_macro2::TokenStream;
use prost_types::field_descriptor_proto::Label;
use prost_types::FieldDescriptorProto;
use quote::{format_ident, quote};
use synapse_gen::ir::Entity;
use synapse_gen::{CodeGenerator, GeneratedFile, GeneratorContext, GeneratorError};

/// Generator that produces SeaORM entity structs.
pub struct EntityGenerator;

impl CodeGenerator for EntityGenerator {
    fn name(&self) -> &str {
        "entity"
    }

    fn generate_entity(
        &self,
        ctx: &GeneratorContext,
        entity: &Entity,
    ) -> Result<Vec<GeneratedFile>, GeneratorError> {
        // Skip if explicitly marked
        if entity.skip {
            return Ok(vec![]);
        }

        // Determine table name
        let table_name = if entity.table_name.is_empty() {
            entity.name.to_snake_case()
        } else {
            entity.table_name.clone()
        };

        // Generate the output filename (in entities/ subdirectory)
        let module_name = entity.name.to_snake_case();
        let output_filename = format!(
            "{}/entities/{}.rs",
            ctx.package.name.replace('.', "/"),
            module_name
        );

        // Generate field definitions
        let fields = generate_fields(entity)?;

        // Generate oneof fields (uses raw descriptor)
        let oneof_fields = generate_oneof_fields(entity);

        // Generate relation fields from entity relations (now using IR Relation type)
        let relation_fields = generate_relation_fields(&entity.relations, &entity.name);

        // Build the entity struct
        let struct_name = format_ident!("Model");
        let table_name_lit = &table_name;

        let field_tokens: Vec<_> = fields
            .iter()
            .map(|f| {
                let name = format_ident!("{}", f.name);
                let ty: syn::Type = syn::parse_str(&f.rust_type).unwrap_or_else(|_| {
                    syn::parse_str::<syn::Type>(&f.rust_type.to_string())
                        .unwrap_or_else(|_| syn::parse_quote!(String))
                });

                let attrs = &f.attributes;
                if attrs.is_empty() {
                    quote! {
                        pub #name: #ty
                    }
                } else {
                    let attr_tokens: Vec<proc_macro2::TokenStream> = attrs
                        .iter()
                        .map(|a| {
                            let attr_content: proc_macro2::TokenStream = a.parse().unwrap();
                            quote! { #[sea_orm(#attr_content)] }
                        })
                        .collect();
                    quote! {
                        #(#attr_tokens)*
                        pub #name: #ty
                    }
                }
            })
            .collect();

        // Combine regular fields, oneof fields, and relation fields
        let all_field_tokens: Vec<TokenStream> = field_tokens
            .into_iter()
            .chain(oneof_fields)
            .chain(relation_fields)
            .collect();

        let code = quote! {
            //! SeaORM entity for the table
            //!
            //! Generated by protoc-gen-synapse from protobuf definition.
            //! @generated

            #![allow(missing_docs)]
            #![allow(unused_imports)]

            use super::super::prelude::*;
            use sea_orm::entity::prelude::*;

            #[sea_orm::model]
            #[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel)]
            #[sea_orm(table_name = #table_name_lit)]
            pub struct #struct_name {
                #(#all_field_tokens),*
            }

            impl ActiveModelBehavior for ActiveModel {}
        };

        // Format the generated code
        let content = code.to_string();
        let formatted = match syn::parse_file(&content) {
            Ok(parsed) => prettyplease::unparse(&parsed),
            Err(_) => content,
        };

        Ok(vec![GeneratedFile {
            path: output_filename,
            content: formatted,
        }])
    }
}

/// Generated field information
struct GeneratedField {
    name: String,
    rust_type: String,
    attributes: Vec<String>,
}

/// Generate field definitions from entity fields (IR)
fn generate_fields(entity: &Entity) -> Result<Vec<GeneratedField>, GeneratorError> {
    let mut fields = Vec::new();

    for field in &entity.fields {
        // Skip oneof fields (they're handled by generate_oneof_fields)
        if is_oneof_field(field.raw, entity.raw) {
            continue;
        }

        let field_name = field
            .raw
            .name
            .as_ref()
            .ok_or_else(|| GeneratorError::Parse("Field has no name".to_string()))?;

        // Get column options from IR (instead of cache lookup)
        let column_options = field.column.as_ref();

        // Determine the Rust type
        let proto_type = field.raw.r#type();
        let type_name = field.raw.type_name.as_deref();
        let mapped = map_proto_type(proto_type, type_name);

        // Check if the field is nullable
        let is_nullable = is_field_nullable(field.raw);

        // Check if this is an embedded field (stored as JSON)
        let is_embedded = column_options.map(|o| o.embed).unwrap_or(false);

        // Build the final Rust type
        let rust_type = if is_embedded {
            let inner_type = extract_embedded_type_name(type_name);
            if is_nullable {
                format!("Option<{}>", inner_type)
            } else {
                inner_type
            }
        } else if is_nullable && !mapped.rust_type.starts_with("Option<") {
            format!("Option<{}>", mapped.rust_type)
        } else {
            mapped.rust_type.clone()
        };

        // Override type if specified in options (but not for embedded fields)
        let rust_type = if !is_embedded {
            if let Some(ref opts) = column_options {
                if !opts.column_type.is_empty() {
                    map_column_type_to_rust(&opts.column_type, is_nullable)
                } else {
                    rust_type
                }
            } else {
                rust_type
            }
        } else {
            rust_type
        };

        // Generate attributes using the column module
        let col_attrs = column::generate_attributes(column_options, &mapped, is_nullable);

        // Use snake_case for field name
        let snake_name = field_name.to_snake_case();

        fields.push(GeneratedField {
            name: snake_name,
            rust_type,
            attributes: col_attrs.attributes,
        });
    }

    Ok(fields)
}

/// Generate fields for all oneofs in a message
fn generate_oneof_fields(entity: &Entity) -> Vec<TokenStream> {
    let oneofs = extract_oneofs(entity.raw);
    let mut fields = Vec::new();

    for oneof in oneofs {
        let oneof_fields = match oneof.strategy {
            OneofStrategy::Flatten => generate_flatten_fields(&oneof, entity.raw),
            OneofStrategy::Json => generate_json_fields(&oneof),
            OneofStrategy::Tagged => generate_tagged_fields(&oneof),
        };
        fields.extend(oneof_fields);
    }

    fields
}

/// Determine if a field should be nullable based on proto definition
fn is_field_nullable(field: &FieldDescriptorProto) -> bool {
    let label = field.label();
    if label == Label::Repeated {
        return false;
    }
    field.proto3_optional.unwrap_or(false)
}

/// Map a SeaORM column type string to a Rust type
fn map_column_type_to_rust(column_type: &str, is_nullable: bool) -> String {
    let base_type = match column_type.to_lowercase().as_str() {
        "uuid" => "Uuid",
        "json" | "jsonb" => "Json",
        "text" => "String",
        "integer" | "int" => "i32",
        "bigint" | "biginteger" => "i64",
        "smallint" | "smallinteger" => "i16",
        "float" => "f32",
        "double" => "f64",
        "decimal" => "Decimal",
        "boolean" | "bool" => "bool",
        "date" => "Date",
        "time" => "Time",
        "datetime" => "DateTime",
        "timestamp" | "timestampwithtimezone" => "DateTimeUtc",
        "binary" | "blob" | "varbinary" => "Vec<u8>",
        _ => column_type,
    };

    if is_nullable {
        format!("Option<{}>", base_type)
    } else {
        base_type.to_string()
    }
}

/// Extract the Rust type name for an embedded field from the protobuf type_name
fn extract_embedded_type_name(type_name: Option<&str>) -> String {
    match type_name {
        Some(name) => {
            let type_part = name
                .rsplit('.')
                .next()
                .unwrap_or(name)
                .trim_start_matches('.');
            use heck::ToUpperCamelCase;
            type_part.to_upper_camel_case()
        }
        None => "serde_json::Value".to_string(),
    }
}
