//! Storage trait generation
//!
//! This module generates backend-agnostic Storage traits from protobuf service
//! definitions. The generated traits mirror service RPCs and can be implemented
//! by database storage layers or mocked for testing.
//!
//! The generated traits support partial overrides:
//! - A required `fn db()` method provides database access
//! - Each operation has a default implementation that calls `defaults::*`
//! - Users can override specific methods while using defaults for others

use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use synapse_gen::ir::options::ValidateMessageOptions;
use synapse_gen::ir::Service;
use synapse_gen::{CodeGenerator, GeneratedFile, GeneratorContext, GeneratorError};

/// Generator that produces backend-agnostic Storage traits.
pub struct StorageTraitGenerator;

impl CodeGenerator for StorageTraitGenerator {
    fn name(&self) -> &str {
        "storage_trait"
    }

    fn generate_service(
        &self,
        ctx: &GeneratorContext,
        service: &Service,
    ) -> Result<Vec<GeneratedFile>, GeneratorError> {
        let storage_options = match &service.storage {
            Some(opts) if !opts.skip && opts.generate_storage => opts,
            _ => return Ok(vec![]),
        };

        let service_name = &service.name;

        // Determine trait name
        let trait_name = if storage_options.trait_name.is_empty() {
            format!("{}Storage", service_name)
        } else {
            storage_options.trait_name.clone()
        };

        // Check if we should generate default implementations
        let generate_defaults = storage_options.generate_implementation;

        // Generate the output filename (in storage/ subdirectory)
        let module_name = trait_name.to_snake_case();
        let output_filename = format!(
            "{}/storage/{}.rs",
            ctx.package.name.replace('.', "/"),
            module_name
        );

        // Generate trait methods (with or without default implementations)
        let methods = generate_trait_methods(ctx, service, generate_defaults, &module_name)?;

        // Build the trait
        let trait_ident = format_ident!("{}", trait_name);

        // Build doc comments
        let module_doc = format!("Storage trait for {}", service_name);
        let trait_doc = format!(
            "Storage trait mirroring {} RPCs.\n\n\
            Implement the required `db()` method and optionally override any operations.\n\
            All operations have default implementations that delegate to the `defaults` module.",
            service_name
        );

        // Import the defaults module if we're generating default implementations
        let defaults_import = if generate_defaults {
            let defaults_module = format_ident!("{}_defaults", module_name);
            quote! {
                use super::#defaults_module as defaults;
            }
        } else {
            quote! {}
        };

        // The db() method - required for all implementations
        let db_method = if generate_defaults {
            quote! {
                /// Get a reference to the database connection.
                ///
                /// This is required for default implementations to work.
                fn db(&self) -> &sea_orm::DatabaseConnection;
            }
        } else {
            quote! {}
        };

        let code = quote! {
            #![doc = #module_doc]
            //!
            //! Generated by protoc-gen-synapse from protobuf service definition.
            //!
            //! This trait supports partial overrides - you can override specific methods
            //! while using default implementations for others. Just implement the required
            //! `db()` method and override the operations you need custom logic for.
            //!
            //! # Example
            //!
            //! ```rust,ignore
            //! struct MyStorage { db: DatabaseConnection }
            //!
            //! impl UserServiceStorage for MyStorage {
            //!     fn db(&self) -> &DatabaseConnection { &self.db }
            //!
            //!     // Override just create_user with custom business logic
            //!     async fn create_user(&self, request: CreateUserRequest) -> Result<CreateUserResponse, StorageError> {
            //!         // Custom validation
            //!         if request.email.is_empty() {
            //!             return Err(StorageError::InvalidArgument("email required".into()));
            //!         }
            //!
            //!         // Call default implementation
            //!         defaults::create_user(self.db(), request).await
            //!     }
            //!
            //!     // All other methods use trait defaults
            //! }
            //! ```
            //!
            //! @generated

            #![allow(missing_docs)]
            #![allow(unused_imports)]

            use super::super::prelude::*;
            #defaults_import

            /// Storage error type
            #[derive(Debug, thiserror::Error)]
            pub enum StorageError {
                /// Database error
                #[error("database error: {0}")]
                Database(#[from] sea_orm::DbErr),
                /// Resource not found
                #[error("not found: {0}")]
                NotFound(String),
                /// Invalid argument
                #[error("invalid argument: {0}")]
                InvalidArgument(String),
            }

            #[doc = #trait_doc]
            #[async_trait::async_trait]
            pub trait #trait_ident: Send + Sync {
                #db_method
                #(#methods)*
            }
        };

        // Format the generated code
        let content = code.to_string();
        let formatted = match syn::parse_file(&content) {
            Ok(parsed) => prettyplease::unparse(&parsed),
            Err(_) => content,
        };

        Ok(vec![GeneratedFile {
            path: output_filename,
            content: formatted,
        }])
    }
}

/// Generate trait method signatures from service methods
fn generate_trait_methods(
    ctx: &GeneratorContext,
    service: &Service,
    generate_defaults: bool,
    _module_name: &str,
) -> Result<Vec<TokenStream>, GeneratorError> {
    let mut result = Vec::new();

    for method in &service.methods {
        let storage_opts = method.storage.as_ref();

        // Skip if marked
        if storage_opts.is_some_and(|o| o.skip) {
            continue;
        }

        // Determine Rust method name
        let rust_method_name = storage_opts
            .filter(|o| !o.method_name.is_empty())
            .map(|o| o.method_name.clone())
            .unwrap_or_else(|| method.name.to_snake_case());

        // Extract input/output types - check for domain type first
        let raw_input_type = extract_type_name(&method.input_type);
        let input_type = resolve_domain_type(ctx, &raw_input_type);
        let output_type = extract_type_name(&method.output_type);

        let method_ident = format_ident!("{}", rust_method_name);
        let input_ident = format_ident!("{}", input_type);
        let output_ident = format_ident!("{}", output_type);

        let method_token = if generate_defaults {
            // Generate method with default implementation that calls defaults::*
            quote! {
                async fn #method_ident(&self, request: #input_ident) -> Result<#output_ident, StorageError> {
                    defaults::#method_ident(self.db(), request).await
                }
            }
        } else {
            // Generate abstract method signature only
            quote! {
                async fn #method_ident(&self, request: #input_ident) -> Result<#output_ident, StorageError>;
            }
        };

        result.push(method_token);
    }

    Ok(result)
}

/// Resolve a message type to its domain type if one exists
fn resolve_domain_type(ctx: &GeneratorContext, message_name: &str) -> String {
    find_validate_options(ctx, message_name)
        .filter(|opts| opts.generate_conversion && !opts.name.is_empty())
        .map(|opts| opts.name.clone())
        .unwrap_or_else(|| message_name.to_string())
}

/// Find ValidateMessageOptions for a message by type name in the current package.
fn find_validate_options<'a>(
    ctx: &'a GeneratorContext,
    type_name: &str,
) -> Option<&'a ValidateMessageOptions> {
    ctx.package
        .messages
        .iter()
        .find(|m| m.name == type_name)
        .and_then(|m| m.validate.as_ref())
        .or_else(|| {
            ctx.package
                .entities
                .iter()
                .find(|e| e.name == type_name)
                .and_then(|e| e.validate.as_ref())
        })
}

/// Extract a Rust type name from a protobuf type path
fn extract_type_name(type_name: &str) -> String {
    let type_part = type_name
        .rsplit('.')
        .next()
        .unwrap_or(type_name)
        .trim_start_matches('.');

    type_part.to_upper_camel_case()
}
