/**
 * Example Resolver Implementations
 *
 * This shows how users implement the generated resolver contracts.
 * These files live in your project (e.g., resolvers/user.ts).
 */

import type {
  User,
  Author,
  Post,
  UserResolverModule,
  AuthorResolverModule,
  PostResolverModule,
  AppResolverContext,
} from "./generated"; // Generated by protoc-gen-synapse

// =============================================================================
// resolvers/user.ts
// =============================================================================

/**
 * Virtual field: User.fullName
 *
 * Computes the user's display name. In this example, just returns
 * the name field, but could combine first/last name, handle i18n, etc.
 */
export const fullName: UserResolverModule["fullName"] = (user) => {
  return user.name;
};

/**
 * Virtual field: User.postCount
 *
 * Counts posts for this user. Uses DataLoader for efficient batching
 * when resolving multiple users in a single query.
 */
export const postCount: UserResolverModule["postCount"] = async (
  user,
  args,
  ctx
) => {
  // Get author profile for this user
  const author = await ctx.dataLoaders.authorByUserId.load(user.id);
  if (!author) return 0;

  // Get posts (uses DataLoader, batched across all users in query)
  const posts = await ctx.dataLoaders.postsByAuthor.load(author.id);

  // Filter by published status if specified
  if (args.published !== undefined) {
    return posts.filter((p) => p.published === args.published).length;
  }

  return posts.length;
};

/**
 * Field override: User.email -> maskEmail
 *
 * Masks the email domain for privacy in public APIs.
 * Only the authenticated user can see their full email.
 */
export const maskEmail: UserResolverModule["maskEmail"] = (user, _args, ctx) => {
  // Show full email to the user themselves
  if (ctx.currentUser?.id === user.id) {
    return user.email;
  }

  // Mask domain for other users
  const [local] = user.email.split("@");
  return `${local}@***`;
};

// =============================================================================
// resolvers/author.ts
// =============================================================================

const WORDS_PER_MINUTE = 200;

/**
 * Virtual field: Author.totalReadingTime
 *
 * Calculates estimated reading time for all posts by this author.
 */
export const totalReadingTime: AuthorResolverModule["totalReadingTime"] = async (
  author,
  _args,
  ctx
) => {
  const posts = await ctx.dataLoaders.postsByAuthor.load(author.id);

  const totalWords = posts.reduce((sum, post) => {
    return sum + post.content.split(/\s+/).length;
  }, 0);

  const minutes = Math.ceil(totalWords / WORDS_PER_MINUTE);

  if (minutes < 60) {
    return `${minutes} min read`;
  }

  const hours = Math.floor(minutes / 60);
  const remainingMinutes = minutes % 60;
  return `${hours}h ${remainingMinutes}m read`;
};

/**
 * Virtual field: Author.popularityScore
 *
 * Simple popularity score based on post count and published ratio.
 * In production, this might call an analytics service.
 */
export const popularityScore: AuthorResolverModule["popularityScore"] = async (
  author,
  _args,
  ctx
) => {
  const posts = await ctx.dataLoaders.postsByAuthor.load(author.id);

  if (posts.length === 0) return 0;

  const publishedCount = posts.filter((p) => p.published).length;
  const publishedRatio = publishedCount / posts.length;

  // Score: post count * published ratio * 10
  return Math.round(posts.length * publishedRatio * 10);
};

// =============================================================================
// resolvers/post.ts
// =============================================================================

/**
 * Virtual field: Post.readingTime
 *
 * Estimated reading time for a single post.
 */
export const readingTime: PostResolverModule["readingTime"] = (post) => {
  const wordCount = post.content.split(/\s+/).length;
  const minutes = Math.ceil(wordCount / WORDS_PER_MINUTE);
  return `${minutes} min read`;
};

/**
 * Virtual field: Post.excerpt
 *
 * Truncated content with ellipsis.
 */
export const excerpt: PostResolverModule["excerpt"] = (post, args) => {
  const length = args.length ?? 200;

  if (post.content.length <= length) {
    return post.content;
  }

  // Truncate at word boundary
  const truncated = post.content.slice(0, length);
  const lastSpace = truncated.lastIndexOf(" ");

  if (lastSpace > length * 0.8) {
    return truncated.slice(0, lastSpace) + "…";
  }

  return truncated + "…";
};

/**
 * Virtual field: Post.wordCount
 *
 * Simple word count.
 */
export const wordCount: PostResolverModule["wordCount"] = (post) => {
  return post.content.split(/\s+/).filter(Boolean).length;
};

// =============================================================================
// resolvers/search.ts (RPC resolver example)
// =============================================================================

import type { BlogServiceResolvers, Connection, Post } from "./generated";

/**
 * Custom RPC resolver: searchPosts
 *
 * Full-text search with pagination. In production, this would
 * call Elasticsearch, Meilisearch, or similar.
 */
export const searchPosts: BlogServiceResolvers["searchPosts"] = async (
  _parent,
  args,
  ctx
) => {
  const { query, first = 10, after } = args;

  // In production: call search service
  // For demo: simple in-memory filter (don't do this in production!)
  const allPosts: Post[] = []; // Would come from search index

  const filtered = allPosts.filter(
    (post) =>
      post.title.toLowerCase().includes(query.toLowerCase()) ||
      post.content.toLowerCase().includes(query.toLowerCase())
  );

  // Simple cursor pagination
  let startIndex = 0;
  if (after) {
    const afterIndex = filtered.findIndex((p) => encodeCursor(p.id) === after);
    startIndex = afterIndex + 1;
  }

  const slice = filtered.slice(startIndex, startIndex + first);
  const hasNextPage = startIndex + first < filtered.length;

  return {
    edges: slice.map((post) => ({
      cursor: encodeCursor(post.id),
      node: post,
    })),
    pageInfo: {
      hasNextPage,
      hasPreviousPage: startIndex > 0,
      startCursor: slice[0] ? encodeCursor(slice[0].id) : undefined,
      endCursor: slice[slice.length - 1]
        ? encodeCursor(slice[slice.length - 1].id)
        : undefined,
    },
    totalCount: filtered.length,
  };
};

// Helper for cursor encoding
function encodeCursor(id: number): string {
  return btoa(`Post:${id}`);
}
