//! gRPC/Tonic service generation
//!
//! This module generates Tonic gRPC service implementations from protobuf
//! service definitions. The generated services delegate to storage traits
//! and handle request validation and error conversion.

use super::errors::generate_error_types;
use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use synapse_gen::ir::options::{GrpcResponseOptions, ValidateMessageOptions};
use synapse_gen::ir::Service;
use synapse_gen::{CodeGenerator, GeneratedFile, GeneratorContext, GeneratorError};

/// Generator that produces Tonic gRPC service implementations.
pub struct GrpcGenerator;

impl CodeGenerator for GrpcGenerator {
    fn name(&self) -> &str {
        "grpc"
    }

    fn generate_service(
        &self,
        ctx: &GeneratorContext,
        service: &Service,
    ) -> Result<Vec<GeneratedFile>, GeneratorError> {
        let grpc_options = match &service.grpc {
            Some(opts) if !opts.skip => opts,
            _ => return Ok(vec![]),
        };

        let service_name = &service.name;

        // Determine struct name
        let struct_name = if grpc_options.struct_name.is_empty() {
            format!("{}GrpcService", service_name)
        } else {
            grpc_options.struct_name.clone()
        };

        // Determine storage trait name
        let storage_trait = if grpc_options.storage_trait.is_empty() {
            format!("{}Storage", service_name)
        } else {
            grpc_options.storage_trait.clone()
        };

        // Generate the output filename (in grpc/ subdirectory)
        let module_name = service_name.to_snake_case();
        let output_filename = format!(
            "{}/grpc/{}.rs",
            ctx.package.name.replace('.', "/"),
            module_name
        );

        // Generate trait methods
        let methods = generate_service_methods(ctx, service)?;

        // Build identifiers
        let struct_ident = format_ident!("{}", struct_name);
        let storage_trait_ident = format_ident!("{}", storage_trait);

        // Build the storage trait module name (snake_case of trait name)
        let storage_trait_module = format!("{}_storage", service_name.to_snake_case());
        let storage_trait_module_ident = format_ident!("{}", storage_trait_module);

        // Build the tonic service trait name (from proto service name)
        let service_module = format!("{}_server", service_name.to_snake_case());
        let service_module_ident = format_ident!("{}", service_module);
        let service_trait_ident = format_ident!("{}", service_name);

        // Build doc comments
        let module_doc = format!("gRPC service implementation for {}", service_name);
        let struct_doc = format!(
            "gRPC service wrapper for {} that delegates to {}",
            service_name, storage_trait
        );

        // Generate error types
        let error_types = generate_error_types();

        let code = quote! {
            #![doc = #module_doc]
            //!
            //! Generated by protoc-gen-synapse from protobuf service definition.
            //! @generated

            #![allow(missing_docs)]
            #![allow(unused_imports)]

            use super::super::prelude::*;
            use super::super::storage::#storage_trait_module_ident::{#storage_trait_ident, StorageError};
            use tonic::{Request, Response, Status};

            #error_types

            #[doc = #struct_doc]
            pub struct #struct_ident<S: #storage_trait_ident + 'static> {
                storage: S,
            }

            impl<S: #storage_trait_ident + 'static> #struct_ident<S> {
                /// Create a new gRPC service with the given storage implementation
                pub fn new(storage: S) -> Self {
                    Self { storage }
                }

                /// Get a reference to the underlying storage
                pub fn storage(&self) -> &S {
                    &self.storage
                }

                /// Get a mutable reference to the underlying storage
                pub fn storage_mut(&mut self) -> &mut S {
                    &mut self.storage
                }

                /// Consume the service and return the storage
                pub fn into_storage(self) -> S {
                    self.storage
                }
            }

            #[tonic::async_trait]
            impl<S: #storage_trait_ident + 'static> #service_module_ident::#service_trait_ident for #struct_ident<S> {
                #(#methods)*
            }
        };

        // Format the generated code
        let content = code.to_string();
        let formatted = match syn::parse_file(&content) {
            Ok(parsed) => prettyplease::unparse(&parsed),
            Err(_) => content,
        };

        Ok(vec![GeneratedFile {
            path: output_filename,
            content: formatted,
        }])
    }
}

/// Generate service method implementations
fn generate_service_methods(
    ctx: &GeneratorContext,
    service: &Service,
) -> Result<Vec<TokenStream>, GeneratorError> {
    let mut result = Vec::new();

    for method in &service.methods {
        let grpc_opts = method.grpc.as_ref();

        // Skip if marked
        if grpc_opts.is_some_and(|o| o.skip) {
            continue;
        }

        // Determine Rust method name
        let rust_method_name = grpc_opts
            .filter(|o| !o.method_name.is_empty())
            .map(|o| o.method_name.clone())
            .unwrap_or_else(|| method.name.to_snake_case());

        // Extract input/output types
        let request_type = extract_type_name(&method.input_type);
        let response_type = extract_type_name(&method.output_type);

        // Check if there's a domain type for validation
        let input_domain_type = grpc_opts
            .filter(|o| !o.input_type.is_empty())
            .map(|o| o.input_type.clone())
            .or_else(|| {
                find_validate_options(ctx, &request_type)
                    .filter(|opts| opts.generate_conversion && !opts.name.is_empty())
                    .map(|opts| opts.name.clone())
            });

        let method_ident = format_ident!("{}", rust_method_name);
        let request_ident = format_ident!("{}", request_type);
        let response_ident = format_ident!("{}", response_type);

        // Check if response type has rich_errors option
        let rich_errors = find_grpc_response_options(ctx, &response_type)
            .map(|opts| opts.rich_errors)
            .unwrap_or(false);

        let method_body = if rich_errors {
            if let Some(domain_type) = input_domain_type {
                let domain_ident = format_ident!("{}", domain_type);
                quote! {
                    // Validate and convert to domain type
                    let validated = match #domain_ident::try_from(request.into_inner()) {
                        Ok(v) => v,
                        Err(e) => {
                            return Ok(Response::new(#response_ident {
                                errors: e.into_errors(),
                                ..Default::default()
                            }));
                        }
                    };

                    self.storage
                        .#method_ident(validated)
                        .await
                        .map(Response::new)
                        .map_err(|e| tonic::Status::from(ServiceError::Storage(e)))
                }
            } else {
                quote! {
                    self.storage
                        .#method_ident(request.into_inner())
                        .await
                        .map(Response::new)
                        .map_err(|e| tonic::Status::from(ServiceError::Storage(e)))
                }
            }
        } else if let Some(domain_type) = input_domain_type {
            let domain_ident = format_ident!("{}", domain_type);
            quote! {
                // Validate and convert to domain type
                let validated = #domain_ident::try_from(request.into_inner())
                    .map_err(|e| tonic::Status::invalid_argument(e.to_string()))?;

                self.storage
                    .#method_ident(validated)
                    .await
                    .map(Response::new)
                    .map_err(|e| tonic::Status::from(ServiceError::Storage(e)))
            }
        } else {
            quote! {
                self.storage
                    .#method_ident(request.into_inner())
                    .await
                    .map(Response::new)
                    .map_err(|e| tonic::Status::from(ServiceError::Storage(e)))
            }
        };

        let method_token = quote! {
            async fn #method_ident(
                &self,
                request: Request<#request_ident>,
            ) -> Result<Response<#response_ident>, Status> {
                #method_body
            }
        };

        result.push(method_token);
    }

    Ok(result)
}

/// Find ValidateMessageOptions for a message by type name in the current package.
fn find_validate_options<'a>(
    ctx: &'a GeneratorContext,
    type_name: &str,
) -> Option<&'a ValidateMessageOptions> {
    // Search messages
    ctx.package
        .messages
        .iter()
        .find(|m| m.name == type_name)
        .and_then(|m| m.validate.as_ref())
        // Also search entities (they can have validate options too)
        .or_else(|| {
            ctx.package
                .entities
                .iter()
                .find(|e| e.name == type_name)
                .and_then(|e| e.validate.as_ref())
        })
}

/// Find GrpcResponseOptions for a message by type name in the current package.
fn find_grpc_response_options<'a>(
    ctx: &'a GeneratorContext,
    type_name: &str,
) -> Option<&'a GrpcResponseOptions> {
    ctx.package
        .messages
        .iter()
        .find(|m| m.name == type_name)
        .and_then(|m| m.grpc_response.as_ref())
}

/// Extract a Rust type name from a protobuf type path
///
/// Converts ".package.name.TypeName" to "TypeName"
fn extract_type_name(type_name: &str) -> String {
    let type_part = type_name
        .rsplit('.')
        .next()
        .unwrap_or(type_name)
        .trim_start_matches('.');

    type_part.to_upper_camel_case()
}
