//! Domain type generation from synapse.validate options
//!
//! This module generates validated domain types from protobuf messages
//! that have `(synapse.validate.message).generate_conversion = true`.
//!
//! Generated code includes:
//! - Domain type struct with validated fields
//! - ValidationError with `into_errors()` for rich error responses
//! - `TryFrom<ProtoMessage>` implementation with validation

use heck::{ToSnakeCase, ToUpperCamelCase};
use proc_macro2::TokenStream;
use quote::{format_ident, quote};
use synapse_gen::ir::options::{ValidateMessageOptions, ValidationRules};
use synapse_gen::ir::{Entity, Field, FieldType, Message};
use synapse_gen::{CodeGenerator, GeneratedFile, GeneratorContext, GeneratorError};

/// Generator that produces validated domain types from synapse.validate annotations.
pub struct ValidateGenerator;

impl CodeGenerator for ValidateGenerator {
    fn name(&self) -> &str {
        "validate"
    }

    fn generate_message(
        &self,
        ctx: &GeneratorContext,
        message: &Message,
    ) -> Result<Vec<GeneratedFile>, GeneratorError> {
        let opts = match &message.validate {
            Some(opts) if opts.generate_conversion && !opts.name.is_empty() => opts,
            _ => return Ok(vec![]),
        };
        generate_domain_type(ctx, &opts.name, &message.name, &message.fields, opts)
    }

    fn generate_entity(
        &self,
        ctx: &GeneratorContext,
        entity: &Entity,
    ) -> Result<Vec<GeneratedFile>, GeneratorError> {
        let opts = match &entity.validate {
            Some(opts) if opts.generate_conversion && !opts.name.is_empty() => opts,
            _ => return Ok(vec![]),
        };
        generate_domain_type(ctx, &opts.name, &entity.name, &entity.fields, opts)
    }
}

/// Shared implementation that generates a domain type from fields and validate options.
fn generate_domain_type(
    ctx: &GeneratorContext,
    domain_name: &str,
    proto_name: &str,
    fields: &[Field],
    _opts: &ValidateMessageOptions,
) -> Result<Vec<GeneratedFile>, GeneratorError> {
    // Generate the output filename
    let module_name = domain_name.to_snake_case();
    let output_filename = format!(
        "{}/{}.rs",
        ctx.package.name.replace('.', "/"),
        module_name,
    );

    // Build identifiers
    let domain_ident = format_ident!("{}", domain_name);
    let proto_ident = format_ident!("{}", proto_name);
    let error_ident = format_ident!("{}ValidationError", domain_name);
    let field_error_ident = format_ident!("{}FieldError", domain_name);

    // Generate field definitions and validation
    let (field_defs, field_validations, field_assignments) =
        generate_fields(fields, &field_error_ident);

    // Build doc comments
    let module_doc = format!("Domain type {} generated from {}", domain_name, proto_name);
    let struct_doc = format!("Validated domain type for {}", proto_name);
    let error_doc = format!("Validation error for {} conversion", domain_name);

    let code = quote! {
        #![doc = #module_doc]
        //!
        //! Generated by protoc-gen-synapse from protobuf message definition.
        //! @generated

        #![allow(missing_docs)]
        #![allow(unused_imports)]

        use super::prelude::*;

        /// A single field validation error
        #[derive(Debug, Clone)]
        pub struct #field_error_ident {
            /// Error code (e.g., "required", "invalid_email", "min_length")
            pub code: String,
            /// Human-readable error message
            pub message: String,
            /// Field name that failed validation
            pub field: String,
        }

        impl std::fmt::Display for #field_error_ident {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "{}: {}", self.field, self.message)
            }
        }

        impl std::error::Error for #field_error_ident {}

        #[doc = #struct_doc]
        #[derive(Debug, Clone)]
        pub struct #domain_ident {
            #(#field_defs)*
        }

        #[doc = #error_doc]
        #[derive(Debug)]
        pub struct #error_ident {
            errors: Vec<#field_error_ident>,
        }

        impl #error_ident {
            /// Convert validation errors to a list of field errors
            pub fn into_errors(self) -> Vec<#field_error_ident> {
                self.errors
            }

            /// Get a reference to the validation errors
            pub fn errors(&self) -> &[#field_error_ident] {
                &self.errors
            }
        }

        impl std::fmt::Display for #error_ident {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                write!(f, "validation failed: {} error(s)", self.errors.len())
            }
        }

        impl std::error::Error for #error_ident {}

        impl TryFrom<#proto_ident> for #domain_ident {
            type Error = #error_ident;

            fn try_from(request: #proto_ident) -> Result<Self, Self::Error> {
                let mut errors = Vec::new();

                #(#field_validations)*

                if !errors.is_empty() {
                    return Err(#error_ident { errors });
                }

                Ok(Self {
                    #(#field_assignments)*
                })
            }
        }
    };

    // Format the generated code
    let content = code.to_string();

    // Try to format with prettyplease if we can parse it
    let formatted = match syn::parse_file(&content) {
        Ok(parsed) => prettyplease::unparse(&parsed),
        Err(_) => content,
    };

    Ok(vec![GeneratedFile {
        path: output_filename,
        content: formatted,
    }])
}

/// Generate field definitions, validations, and assignments
fn generate_fields(
    fields: &[Field],
    field_error_ident: &proc_macro2::Ident,
) -> (Vec<TokenStream>, Vec<TokenStream>, Vec<TokenStream>) {
    let mut field_defs = Vec::new();
    let mut field_validations = Vec::new();
    let mut field_assignments = Vec::new();

    for field in fields {
        let field_ident = format_ident!("{}", field.name.to_snake_case());

        // Look up field-level validate options
        let field_opts = field.validation.as_ref();

        // Skip this field if marked as skip
        if field_opts.is_some_and(|opts| opts.skip) {
            continue;
        }

        // Check if field has custom type
        let custom_type = field_opts.and_then(|opts| {
            if opts.field_type.is_empty() {
                None
            } else {
                Some(opts.field_type.clone())
            }
        });

        // Determine Rust type based on IR field type or custom type
        let rust_type = if let Some(ref type_name) = custom_type {
            let type_ident = format_ident!("{}", type_name);
            quote! { #type_ident }
        } else {
            field_type_to_rust_token(&field.field_type, field.nullable, field.repeated)
        };

        // Generate field definition
        field_defs.push(quote! {
            pub #field_ident: #rust_type,
        });

        // Generate validation code based on field options
        if let Some(opts) = field_opts {
            if let Some(ref rules) = opts.rules {
                let validation = generate_field_validation(
                    &field.name,
                    &field_ident,
                    field,
                    rules,
                    field_error_ident,
                );
                if !validation.is_empty() {
                    field_validations.push(validation);
                }
            }
        }

        // Generate field assignment (with type conversion if custom type)
        if custom_type.is_some() {
            let type_ident = format_ident!("{}", custom_type.unwrap());
            let field_name_str = &field.name;
            field_assignments.push(quote! {
                #field_ident: #type_ident::from_str(&request.#field_ident)
                    .map_err(|e| errors.push(#field_error_ident {
                        code: "invalid_format".to_string(),
                        message: e.to_string(),
                        field: #field_name_str.to_string(),
                    }))
                    .unwrap_or_default(),
            });
        } else {
            field_assignments.push(quote! {
                #field_ident: request.#field_ident,
            });
        }
    }

    (field_defs, field_validations, field_assignments)
}

/// Generate validation code for a field based on its rules
fn generate_field_validation(
    field_name: &str,
    field_ident: &proc_macro2::Ident,
    field: &Field,
    rules: &ValidationRules,
    field_error_ident: &proc_macro2::Ident,
) -> TokenStream {
    let mut validations = Vec::new();
    let is_optional = field.nullable;
    let is_string = matches!(field.field_type, FieldType::String);
    let is_bytes = matches!(field.field_type, FieldType::Bytes);

    // Required validation
    if rules.required {
        if is_optional {
            // For optional fields, required means it must be Some
            validations.push(quote! {
                if request.#field_ident.is_none() {
                    errors.push(#field_error_ident {
                        code: "required".to_string(),
                        message: format!("{} is required", #field_name),
                        field: #field_name.to_string(),
                    });
                }
            });
        } else if is_string || is_bytes {
            // For strings/bytes, required means non-empty
            validations.push(quote! {
                if request.#field_ident.is_empty() {
                    errors.push(#field_error_ident {
                        code: "required".to_string(),
                        message: format!("{} is required", #field_name),
                        field: #field_name.to_string(),
                    });
                }
            });
        }
        // For numeric types, there's no meaningful "required" check since 0 is a valid value
        // The field is always present in proto3
    }

    // String-specific validations - only apply to string fields
    if is_string {
        // Email validation
        if rules.email {
            if is_optional {
                validations.push(quote! {
                    if let Some(ref value) = request.#field_ident {
                        if !value.is_empty() && !value.contains('@') {
                            errors.push(#field_error_ident {
                                code: "invalid_email".to_string(),
                                message: format!("{} must be a valid email address", #field_name),
                                field: #field_name.to_string(),
                            });
                        }
                    }
                });
            } else {
                validations.push(quote! {
                    if !request.#field_ident.is_empty() && !request.#field_ident.contains('@') {
                        errors.push(#field_error_ident {
                            code: "invalid_email".to_string(),
                            message: format!("{} must be a valid email address", #field_name),
                            field: #field_name.to_string(),
                        });
                    }
                });
            }
        }

        // Length validation
        if let Some(ref length) = rules.length {
            // Min length validation
            if length.min.is_some() && length.min.unwrap() > 0 {
                let min_val = length.min.unwrap() as usize;
                if is_optional {
                    validations.push(quote! {
                        if let Some(ref value) = request.#field_ident {
                            if value.len() < #min_val {
                                errors.push(#field_error_ident {
                                    code: "min_length".to_string(),
                                    message: format!("{} must be at least {} characters", #field_name, #min_val),
                                    field: #field_name.to_string(),
                                });
                            }
                        }
                    });
                } else {
                    validations.push(quote! {
                        if request.#field_ident.len() < #min_val {
                            errors.push(#field_error_ident {
                                code: "min_length".to_string(),
                                message: format!("{} must be at least {} characters", #field_name, #min_val),
                                field: #field_name.to_string(),
                            });
                        }
                    });
                }
            }

            // Max length validation
            if length.max.is_some() && length.max.unwrap() > 0 {
                let max_val = length.max.unwrap() as usize;
                if is_optional {
                    validations.push(quote! {
                        if let Some(ref value) = request.#field_ident {
                            if value.len() > #max_val {
                                errors.push(#field_error_ident {
                                    code: "max_length".to_string(),
                                    message: format!("{} must be at most {} characters", #field_name, #max_val),
                                    field: #field_name.to_string(),
                                });
                            }
                        }
                    });
                } else {
                    validations.push(quote! {
                        if request.#field_ident.len() > #max_val {
                            errors.push(#field_error_ident {
                                code: "max_length".to_string(),
                                message: format!("{} must be at most {} characters", #field_name, #max_val),
                                field: #field_name.to_string(),
                            });
                        }
                    });
                }
            }

            // Equal length validation
            if length.equal.is_some() && length.equal.unwrap() > 0 {
                let equal_val = length.equal.unwrap() as usize;
                if is_optional {
                    validations.push(quote! {
                        if let Some(ref value) = request.#field_ident {
                            if value.len() != #equal_val {
                                errors.push(#field_error_ident {
                                    code: "exact_length".to_string(),
                                    message: format!("{} must be exactly {} characters", #field_name, #equal_val),
                                    field: #field_name.to_string(),
                                });
                            }
                        }
                    });
                } else {
                    validations.push(quote! {
                        if request.#field_ident.len() != #equal_val {
                            errors.push(#field_error_ident {
                                code: "exact_length".to_string(),
                                message: format!("{} must be exactly {} characters", #field_name, #equal_val),
                                field: #field_name.to_string(),
                            });
                        }
                    });
                }
            }
        }

        // Pattern validation
        if !rules.pattern.is_empty() {
            let pattern = &rules.pattern;
            if is_optional {
                validations.push(quote! {
                    if let Some(ref value) = request.#field_ident {
                        let re = regex::Regex::new(#pattern).expect("invalid regex pattern");
                        if !re.is_match(value) {
                            errors.push(#field_error_ident {
                                code: "pattern".to_string(),
                                message: format!("{} does not match required pattern", #field_name),
                                field: #field_name.to_string(),
                            });
                        }
                    }
                });
            } else {
                validations.push(quote! {
                    {
                        let re = regex::Regex::new(#pattern).expect("invalid regex pattern");
                        if !re.is_match(&request.#field_ident) {
                            errors.push(#field_error_ident {
                                code: "pattern".to_string(),
                                message: format!("{} does not match required pattern", #field_name),
                                field: #field_name.to_string(),
                            });
                        }
                    }
                });
            }
        }
    }

    quote! {
        #(#validations)*
    }
}

/// Convert an IR `FieldType` to a Rust type `TokenStream`, wrapping in
/// `Option<..>` when nullable and `Vec<..>` when repeated.
fn field_type_to_rust_token(ft: &FieldType, nullable: bool, repeated: bool) -> TokenStream {
    let base_type = match ft {
        FieldType::Double => quote! { f64 },
        FieldType::Float => quote! { f32 },
        FieldType::Int64 | FieldType::SFixed64 | FieldType::SInt64 => quote! { i64 },
        FieldType::UInt64 | FieldType::Fixed64 => quote! { u64 },
        FieldType::Int32 | FieldType::SFixed32 | FieldType::SInt32 => quote! { i32 },
        FieldType::UInt32 | FieldType::Fixed32 => quote! { u32 },
        FieldType::Bool => quote! { bool },
        FieldType::String => quote! { String },
        FieldType::Bytes => quote! { Vec<u8> },
        FieldType::Timestamp => {
            let ident = format_ident!("Timestamp");
            quote! { #ident }
        }
        FieldType::Duration => {
            let ident = format_ident!("Duration");
            quote! { #ident }
        }
        FieldType::Struct => {
            let ident = format_ident!("Value");
            quote! { #ident }
        }
        FieldType::Message(name) | FieldType::Enum(name) => {
            let last_segment = name.rsplit('.').next().unwrap_or(name);
            let ident = format_ident!("{}", last_segment.to_upper_camel_case());
            quote! { #ident }
        }
    };

    if repeated {
        quote! { Vec<#base_type> }
    } else if nullable {
        quote! { Option<#base_type> }
    } else {
        base_type
    }
}
