use std::path::PathBuf;
use std::process::Command;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed=proto/");
    println!("cargo:rerun-if-changed=../../protoc-gen-synapse/");

    let src_generated = PathBuf::from("src/generated");
    std::fs::create_dir_all(&src_generated)?;

    // Generate gRPC code with tonic (to OUT_DIR for include_proto!)
    tonic_build::configure()
        .build_server(true)
        .build_client(true)
        .compile_protos(
            &["proto/blog.proto"],
            &["proto/", "../../proto/"],
        )?;

    // Generate Synapse code (SeaORM entities, storage traits, implementations)
    // First, build protoc-gen-synapse in release mode
    let build_status = Command::new("cargo")
        .args([
            "build",
            "--release",
            "--manifest-path",
            "../../protoc-gen-synapse/Cargo.toml",
        ])
        .status()?;

    if !build_status.success() {
        println!("cargo:warning=Failed to build protoc-gen-synapse");
        return Ok(());
    }

    // Run protoc with our plugin (to src/generated for direct imports)
    let status = Command::new("protoc")
        .args([
            "--plugin=protoc-gen-synapse=../../protoc-gen-synapse/target/release/protoc-gen-synapse",
            &format!("--synapse_out=backend=seaorm:{}", src_generated.display()),
            "-I../../proto",
            "-Iproto",
            "proto/blog.proto",
        ])
        .status();

    match status {
        Ok(s) if s.success() => println!("cargo:warning=Synapse code generation succeeded"),
        Ok(s) => println!("cargo:warning=Synapse code generation failed with: {}", s),
        Err(e) => println!("cargo:warning=Failed to run protoc-gen-synapse: {}", e),
    }

    // Create a mod.rs file that includes all generated modules
    let mod_content = r#"//! Generated code from proto definitions
//!
//! This module is auto-generated by build.rs

#![allow(missing_docs)]
#![allow(unused_imports)]
#![allow(clippy::all)]
#![allow(dead_code)]

// Synapse-generated code is in the blog/ subdirectory
pub mod blog;
"#;

    std::fs::write(src_generated.join("mod.rs"), mod_content)?;

    Ok(())
}
