//! TypeScript type generation from protobuf messages
//!
//! This module generates TypeScript interface definitions from protobuf messages,
//! primarily for use with custom Deno resolvers. It creates type-safe contracts
//! that resolvers must implement.
//!
//! Generated files:
//! - `types.d.ts` - Interface definitions for proto messages
//! - `resolvers.d.ts` - Resolver contracts
//! - `dataloaders.d.ts` - DataLoader interfaces

use heck::{ToLowerCamelCase, ToUpperCamelCase};
use prost_types::field_descriptor_proto::{Label, Type};
use prost_types::{DescriptorProto, FieldDescriptorProto};
use synapse_gen::ir::options::{DenoConfig, GraphQLResolverOptions, VirtualField};
use synapse_gen::ir::{Field, RelationType, Service};
use synapse_gen::{CodeGenerator, GeneratedFile, GeneratorContext, GeneratorError};

/// TypeScript code generator using synapse-gen IR.
pub struct TypeScriptGenerator;

impl TypeScriptGenerator {
    /// Generate TypeScript types for all entities and GraphQL-annotated messages in a package
    fn generate_types(ctx: &GeneratorContext) -> Option<GeneratedFile> {
        let package = &ctx.package.name;

        let mut interfaces = Vec::new();

        // Generate interfaces for entities
        for entity in &ctx.package.entities {
            if let Some(interface) =
                generate_interface(&entity.name, entity.raw, entity.graphql_resolver.as_ref())
            {
                interfaces.push(interface);
            }
        }

        // Generate interfaces for non-entity messages with graphql options
        for msg in &ctx.package.messages {
            if msg.graphql.is_some() {
                if let Some(interface) =
                    generate_interface(&msg.name, msg.raw, msg.graphql_resolver.as_ref())
                {
                    interfaces.push(interface);
                }
            }
        }

        if interfaces.is_empty() {
            return None;
        }

        let output_filename = format!("{}/typescript/types.d.ts", package.replace('.', "/"));

        let content = format!(
            r#"/**
 * TypeScript type definitions generated from protobuf messages
 *
 * @generated by protoc-gen-synapse
 * DO NOT EDIT MANUALLY
 */

// =============================================================================
// Utility Types
// =============================================================================

/** Nullable type for optional proto fields */
export type Nullable<T> = T | null | undefined;

// =============================================================================
// Message Types
// =============================================================================

{}
"#,
            interfaces.join("\n\n")
        );

        Some(GeneratedFile {
            path: output_filename,
            content,
        })
    }

    /// Generate TypeScript resolver contracts for all messages in a package
    fn generate_resolvers(ctx: &GeneratorContext) -> Option<GeneratedFile> {
        let package = &ctx.package.name;

        let mut virtual_field_interfaces = Vec::new();
        let mut field_override_interfaces = Vec::new();
        let mut module_contracts = Vec::new();
        let mut imports = std::collections::HashSet::new();

        // Process entities with resolver options
        for entity in &ctx.package.entities {
            if let Some(ref resolver_opts) = entity.graphql_resolver {
                if !resolver_opts.fields.is_empty() {
                    imports.insert(entity.name.clone());
                    if let Some(interface) =
                        generate_virtual_field_interface(&entity.name, &resolver_opts.fields)
                    {
                        virtual_field_interfaces.push(interface);
                    }
                    if let Some(module) = generate_resolver_module(
                        &entity.name,
                        &resolver_opts.fields,
                        resolver_opts.deno.as_ref(),
                    ) {
                        module_contracts.push(module);
                    }
                }
            }

            // Check for field-level resolver overrides
            let field_overrides = collect_field_overrides(&entity.fields, entity.raw);
            if !field_overrides.is_empty() {
                imports.insert(entity.name.clone());
                if let Some(interface) =
                    generate_field_override_interface(&entity.name, entity.raw, &field_overrides)
                {
                    field_override_interfaces.push(interface);
                }
            }
        }

        // Process non-entity messages with resolver options
        for msg in &ctx.package.messages {
            if let Some(ref resolver_opts) = msg.graphql_resolver {
                if !resolver_opts.fields.is_empty() {
                    imports.insert(msg.name.clone());
                    if let Some(interface) =
                        generate_virtual_field_interface(&msg.name, &resolver_opts.fields)
                    {
                        virtual_field_interfaces.push(interface);
                    }
                    if let Some(module) = generate_resolver_module(
                        &msg.name,
                        &resolver_opts.fields,
                        resolver_opts.deno.as_ref(),
                    ) {
                        module_contracts.push(module);
                    }
                }
            }

            // Check for field-level resolver overrides
            let field_overrides = collect_field_overrides(&msg.fields, msg.raw);
            if !field_overrides.is_empty() {
                imports.insert(msg.name.clone());
                if let Some(interface) =
                    generate_field_override_interface(&msg.name, msg.raw, &field_overrides)
                {
                    field_override_interfaces.push(interface);
                }
            }
        }

        // Check for RPC resolver overrides in services
        let mut rpc_interfaces = Vec::new();
        for service in &ctx.package.services {
            if let Some(interface) = generate_rpc_resolver_interface(service) {
                rpc_interfaces.push(interface);
            }
        }

        // If no resolver contracts, don't generate the file
        if virtual_field_interfaces.is_empty()
            && field_override_interfaces.is_empty()
            && rpc_interfaces.is_empty()
        {
            return None;
        }

        // Build imports
        let import_list: Vec<_> = imports.into_iter().collect();
        let imports_section = if import_list.is_empty() {
            String::new()
        } else {
            format!(
                "import type {{ {} }} from \"./types\";\n\n",
                import_list.join(", ")
            )
        };

        // Build content sections
        let mut sections = Vec::new();

        if !virtual_field_interfaces.is_empty() {
            sections.push(format!(
                "// =============================================================================\n\
                 // Virtual Field Resolvers\n\
                 // =============================================================================\n\n\
                 {}",
                virtual_field_interfaces.join("\n\n")
            ));
        }

        if !field_override_interfaces.is_empty() {
            sections.push(format!(
                "// =============================================================================\n\
                 // Field Override Resolvers\n\
                 // =============================================================================\n\n\
                 {}",
                field_override_interfaces.join("\n\n")
            ));
        }

        if !rpc_interfaces.is_empty() {
            sections.push(format!(
                "// =============================================================================\n\
                 // RPC Resolvers\n\
                 // =============================================================================\n\n\
                 {}",
                rpc_interfaces.join("\n\n")
            ));
        }

        if !module_contracts.is_empty() {
            sections.push(format!(
                "// =============================================================================\n\
                 // Module Export Contracts\n\
                 // =============================================================================\n\n\
                 {}",
                module_contracts.join("\n\n")
            ));
        }

        let output_filename = format!("{}/typescript/resolvers.d.ts", package.replace('.', "/"));

        let content = format!(
            r#"/**
 * TypeScript resolver contracts generated from protobuf options
 *
 * These interfaces define the type-safe contract for custom Deno resolvers.
 * Implement the required module exports to provide custom resolver logic.
 *
 * @generated by protoc-gen-synapse
 * DO NOT EDIT MANUALLY
 */

import type {{ FieldResolver, RootResolver, ResolverContext }} from "@synapse/runtime";
{}{}
"#,
            imports_section,
            sections.join("\n\n")
        );

        Some(GeneratedFile {
            path: output_filename,
            content,
        })
    }

    /// Generate DataLoader interfaces for a package
    fn generate_dataloaders(ctx: &GeneratorContext) -> Option<GeneratedFile> {
        let package = &ctx.package.name;

        let mut loaders = Vec::new();
        let mut type_imports = std::collections::HashSet::new();

        // Collect entities in this package
        for entity in &ctx.package.entities {
            type_imports.insert(entity.name.clone());

            // Generate {entity}ById loader
            loaders.push(DataLoaderDef {
                name: format!("{}ById", entity.name.to_lower_camel_case()),
                key_type: "number".to_string(),
                value_type: format!("{} | null", entity.name),
                description: format!("Load {} by primary key", entity.name),
            });

            // Generate loaders for has_many relations
            for relation in &entity.relations {
                if relation.relation_type == RelationType::HasMany {
                    let related_type = extract_type_name(&relation.related);
                    let fk_camel = relation.foreign_key.to_upper_camel_case();

                    loaders.push(DataLoaderDef {
                        name: format!(
                            "{}By{}",
                            related_type.to_lower_camel_case() + "s",
                            fk_camel
                        ),
                        key_type: "number".to_string(),
                        value_type: format!("{}[]", related_type),
                        description: format!(
                            "Load {} by {} (has_many)",
                            related_type, relation.foreign_key
                        ),
                    });

                    // Add the related type to imports if in same package
                    if !relation.related.contains('.') {
                        type_imports.insert(related_type);
                    }
                }
            }
        }

        if loaders.is_empty() {
            return None;
        }

        // Build imports
        let import_list: Vec<_> = type_imports.into_iter().collect();
        let imports_section = format!(
            "import type {{ {} }} from \"./types\";\n\n",
            import_list.join(", ")
        );

        // Build loader definitions
        let loader_defs: Vec<String> = loaders
            .iter()
            .map(|loader| {
                format!(
                    "  /** {} */\n  {}: DataLoader<{}, {}>;",
                    loader.description, loader.name, loader.key_type, loader.value_type
                )
            })
            .collect();

        let output_filename = format!("{}/typescript/dataloaders.d.ts", package.replace('.', "/"));

        let content = format!(
            r#"/**
 * DataLoader interfaces generated from entity relations
 *
 * These typed DataLoaders enable efficient batched data fetching
 * for GraphQL resolvers.
 *
 * @generated by protoc-gen-synapse
 * DO NOT EDIT MANUALLY
 */

import type {{ DataLoader }} from "@synapse/runtime";
{}// =============================================================================
// DataLoader Interface
// =============================================================================

/**
 * Generated DataLoaders for this package.
 *
 * Usage in resolvers:
 * ```typescript
 * const user = await ctx.dataLoaders.userById.load(userId);
 * ```
 */
export interface GeneratedDataLoaders {{
{}
}}
"#,
            imports_section,
            loader_defs.join("\n")
        );

        Some(GeneratedFile {
            path: output_filename,
            content,
        })
    }
}

impl CodeGenerator for TypeScriptGenerator {
    fn name(&self) -> &str {
        "typescript"
    }

    fn finalize_package(
        &self,
        ctx: &GeneratorContext,
    ) -> Result<Vec<GeneratedFile>, GeneratorError> {
        let mut files = Vec::new();

        if let Some(types) = Self::generate_types(ctx) {
            files.push(types);
        }
        if let Some(resolvers) = Self::generate_resolvers(ctx) {
            files.push(resolvers);
        }
        if let Some(dataloaders) = Self::generate_dataloaders(ctx) {
            files.push(dataloaders);
        }

        Ok(files)
    }
}

// =============================================================================
// Helper types and functions
// =============================================================================

/// Represents a DataLoader definition
struct DataLoaderDef {
    /// Loader name (e.g., "userById", "postsByAuthorId")
    name: String,
    /// Key type (e.g., "number")
    key_type: String,
    /// Value type (e.g., "User | null", "Post[]")
    value_type: String,
    /// Description for JSDoc
    description: String,
}

/// Represents a field with resolver override
struct FieldOverride {
    field_name: String,
    field_number: i32,
    ts_type: String,
}

/// Generate a TypeScript interface from a proto message
fn generate_interface(
    msg_name: &str,
    raw: &DescriptorProto,
    resolver_opts: Option<&GraphQLResolverOptions>,
) -> Option<String> {
    // Generate fields
    let mut fields = Vec::new();
    for field in &raw.field {
        if let Some(field_def) = generate_field(field) {
            fields.push(field_def);
        }
    }

    // Check for resolver options to add virtual fields
    if let Some(resolver_opts) = resolver_opts {
        for virtual_field in &resolver_opts.fields {
            let field_name = virtual_field.name.to_lower_camel_case();
            let field_type = graphql_type_to_typescript(&virtual_field.field_type);
            let comment = virtual_field
                .description
                .as_ref()
                .map(|d| format!("  /** {} */\n", d))
                .unwrap_or_default();
            fields.push(format!("{}  {}: {};", comment, field_name, field_type));
        }
    }

    if fields.is_empty() {
        return None;
    }

    let interface = format!(
        r#"export interface {} {{
{}
}}"#,
        msg_name,
        fields.join("\n")
    );

    Some(interface)
}

/// Generate a TypeScript field definition from a proto field
fn generate_field(field: &FieldDescriptorProto) -> Option<String> {
    let field_name = field.name.as_deref().unwrap_or("");
    let ts_name = field_name.to_lower_camel_case();

    // Get the TypeScript type
    let ts_type = proto_type_to_typescript(field);

    // Check if optional - in proto3, only fields with explicit 'optional' keyword
    // proto3_optional() returns true for fields marked with 'optional' keyword
    let is_optional = field.proto3_optional();
    let is_repeated = field.label() == Label::Repeated;

    // Message types are always nullable (can be unset)
    let is_message = field.r#type() == Type::Message;

    let full_type = if is_repeated {
        format!("{}[]", ts_type)
    } else if is_optional || is_message {
        format!("Nullable<{}>", ts_type)
    } else {
        ts_type
    };

    Some(format!("  {}: {};", ts_name, full_type))
}

/// Convert a proto field type to TypeScript type
fn proto_type_to_typescript(field: &FieldDescriptorProto) -> String {
    match field.r#type() {
        Type::Double | Type::Float => "number".to_string(),
        Type::Int64 | Type::Uint64 | Type::Sint64 | Type::Fixed64 | Type::Sfixed64 => {
            "number".to_string() // BigInt would be more accurate but number is more convenient
        }
        Type::Int32 | Type::Uint32 | Type::Sint32 | Type::Fixed32 | Type::Sfixed32 => {
            "number".to_string()
        }
        Type::Bool => "boolean".to_string(),
        Type::String => "string".to_string(),
        Type::Bytes => "Uint8Array".to_string(),
        Type::Enum => {
            // Get enum type name
            field
                .type_name
                .as_ref()
                .map(|t| extract_type_name(t))
                .unwrap_or_else(|| "number".to_string())
        }
        Type::Message => {
            // Get message type name
            let type_name = field
                .type_name
                .as_ref()
                .map(|t| extract_type_name(t))
                .unwrap_or_else(|| "unknown".to_string());

            // Handle well-known types
            match type_name.as_str() {
                "Timestamp" => "string".to_string(), // ISO 8601 format
                "Duration" => "string".to_string(),
                "Any" => "unknown".to_string(),
                "Struct" => "Record<string, unknown>".to_string(),
                "Value" => "unknown".to_string(),
                "ListValue" => "unknown[]".to_string(),
                "BoolValue" | "StringValue" | "BytesValue" | "DoubleValue" | "FloatValue"
                | "Int32Value" | "Int64Value" | "UInt32Value" | "UInt64Value" => {
                    // Wrapper types - unwrap to the inner type, nullable
                    match type_name.as_str() {
                        "BoolValue" => "Nullable<boolean>".to_string(),
                        "StringValue" => "Nullable<string>".to_string(),
                        "BytesValue" => "Nullable<Uint8Array>".to_string(),
                        _ => "Nullable<number>".to_string(),
                    }
                }
                _ => type_name,
            }
        }
        Type::Group => "unknown".to_string(), // Deprecated
    }
}

/// Convert a GraphQL type string to TypeScript
fn graphql_type_to_typescript(graphql_type: &str) -> String {
    let trimmed = graphql_type.trim();

    // Check for non-null (!)
    let (base_type, is_required) = if trimmed.ends_with('!') {
        (&trimmed[..trimmed.len() - 1], true)
    } else {
        (trimmed, false)
    };

    // Check for list ([...])
    if base_type.starts_with('[') && base_type.ends_with(']') {
        let inner = &base_type[1..base_type.len() - 1];
        let inner_ts = graphql_type_to_typescript(inner);
        let array_type = format!("{}[]", inner_ts);
        if is_required {
            array_type
        } else {
            format!("Nullable<{}>", array_type)
        }
    } else {
        // Scalar type
        let ts_type = match base_type {
            "String" | "ID" => "string",
            "Int" | "Float" => "number",
            "Boolean" => "boolean",
            _ => base_type, // Custom type, use as-is
        };

        if is_required {
            ts_type.to_string()
        } else {
            format!("Nullable<{}>", ts_type)
        }
    }
}

/// Extract the type name from a fully-qualified proto type name
fn extract_type_name(type_name: &str) -> String {
    type_name
        .rsplit('.')
        .next()
        .unwrap_or(type_name)
        .to_string()
}

/// Generate interface for virtual field resolvers
fn generate_virtual_field_interface(msg_name: &str, fields: &[VirtualField]) -> Option<String> {
    if fields.is_empty() {
        return None;
    }

    let mut field_defs = Vec::new();
    for field in fields {
        let field_name = field.name.to_lower_camel_case();
        let result_type = graphql_type_to_typescript(&field.field_type);

        // Build args type
        let args_type = if field.arguments.is_empty() {
            "Record<string, never>".to_string()
        } else {
            let arg_fields: Vec<String> = field
                .arguments
                .iter()
                .map(|arg| {
                    let arg_name = arg.name.to_lower_camel_case();
                    let arg_type = graphql_type_to_typescript(&arg.field_type);
                    // Check if optional (no ! at end or has default)
                    let is_optional =
                        !arg.field_type.ends_with('!') || arg.default_value.is_some();
                    if is_optional {
                        format!(
                            "{}?: {}",
                            arg_name,
                            arg_type
                                .trim_start_matches("Nullable<")
                                .trim_end_matches('>')
                        )
                    } else {
                        format!("{}: {}", arg_name, arg_type)
                    }
                })
                .collect();
            format!("{{ {} }}", arg_fields.join("; "))
        };

        // Add description as JSDoc if present
        let comment = field
            .description
            .as_ref()
            .map(|d| format!("  /** {} */\n", d))
            .unwrap_or_default();

        field_defs.push(format!(
            "{}  {}: FieldResolver<{}, {}, {}>;",
            comment, field_name, msg_name, args_type, result_type
        ));
    }

    Some(format!(
        "/** Virtual field resolvers for {} */\n\
         export interface {}VirtualFields {{\n\
         {}\n\
         }}",
        msg_name,
        msg_name,
        field_defs.join("\n")
    ))
}

/// Generate interface for field override resolvers
fn generate_field_override_interface(
    msg_name: &str,
    message: &DescriptorProto,
    overrides: &[FieldOverride],
) -> Option<String> {
    if overrides.is_empty() {
        return None;
    }

    let mut field_defs = Vec::new();
    for override_field in overrides {
        // Find the original field to get its type
        let original_field = message
            .field
            .iter()
            .find(|f| f.number == Some(override_field.field_number));

        let result_type = if let Some(field) = original_field {
            proto_type_to_typescript(field)
        } else {
            override_field.ts_type.clone()
        };

        field_defs.push(format!(
            "  {}: FieldResolver<{}, Record<string, never>, {}>;",
            override_field.field_name, msg_name, result_type
        ));
    }

    Some(format!(
        "/** Field override resolvers for {} */\n\
         export interface {}FieldOverrides {{\n\
         {}\n\
         }}",
        msg_name,
        msg_name,
        field_defs.join("\n")
    ))
}

/// Generate resolver module export contract
fn generate_resolver_module(
    msg_name: &str,
    fields: &[VirtualField],
    _deno_config: Option<&DenoConfig>,
) -> Option<String> {
    if fields.is_empty() {
        return None;
    }

    let field_names: Vec<String> = fields
        .iter()
        .map(|f| f.name.to_lower_camel_case())
        .collect();

    let field_refs: Vec<String> = field_names
        .iter()
        .map(|name| format!("  {}: {}VirtualFields[\"{}\"];", name, msg_name, name))
        .collect();

    let first_field = field_names.first().map(|s| s.as_str()).unwrap_or("");

    Some(format!(
        r#"/**
 * Module export contract for {} resolvers.
 *
 * Your Deno module must export these functions:
 * ```typescript
 * export const {}: {}ResolverModule["{}"]
 * ```
 */
export interface {}ResolverModule {{
{}
}}"#,
        msg_name,
        first_field,
        msg_name,
        first_field,
        msg_name,
        field_refs.join("\n")
    ))
}

/// Collect fields with resolver overrides from IR fields
fn collect_field_overrides(fields: &[Field], raw: &DescriptorProto) -> Vec<FieldOverride> {
    let mut overrides = Vec::new();
    for field in fields {
        if field.graphql_resolver.is_some() {
            // Find the raw proto field to get its type for TypeScript conversion
            let raw_field = raw.field.iter().find(|f| f.number == Some(field.number));
            let ts_type = raw_field
                .map(|f| proto_type_to_typescript(f))
                .unwrap_or_else(|| "unknown".to_string());
            overrides.push(FieldOverride {
                field_name: field.name.to_lower_camel_case(),
                field_number: field.number,
                ts_type,
            });
        }
    }
    overrides
}

/// Generate RPC resolver interface for a service
fn generate_rpc_resolver_interface(service: &Service) -> Option<String> {
    let mut method_defs = Vec::new();

    for method in &service.methods {
        if method.graphql_resolver.is_some() {
            let ts_method_name = method.name.to_lower_camel_case();

            let input_type = extract_type_name(&method.input_type);
            let output_type = extract_type_name(&method.output_type);

            method_defs.push(format!(
                "  {}: RootResolver<{}, {}>;",
                ts_method_name, input_type, output_type
            ));
        }
    }

    if method_defs.is_empty() {
        return None;
    }

    Some(format!(
        "/** Custom RPC resolvers for {} */\n\
         export interface {}Resolvers {{\n\
         {}\n\
         }}",
        service.name,
        service.name,
        method_defs.join("\n")
    ))
}
