//! TypeScript type generation from protobuf messages
//!
//! This module generates TypeScript interface definitions from protobuf messages,
//! primarily for use with custom Deno resolvers. It creates type-safe contracts
//! that resolvers must implement.
//!
//! Generated files:
//! - `types.d.ts` - Interface definitions for proto messages
//! - `resolvers.d.ts` - Resolver contracts (future, synapse-9ln)

use crate::error::GeneratorError;
use crate::storage::seaorm::options::{
    get_cached_entity_options, get_cached_graphql_resolver_options, get_cached_graphql_type_options,
};
use heck::ToLowerCamelCase;
use prost_types::compiler::code_generator_response::File;
use prost_types::field_descriptor_proto::{Label, Type};
use prost_types::{DescriptorProto, FieldDescriptorProto, FileDescriptorProto};

/// Generate TypeScript types for all messages in a package
pub fn generate_types(
    file: &FileDescriptorProto,
    all_files: &[FileDescriptorProto],
) -> Result<Option<File>, GeneratorError> {
    let _file_name = file.name.as_deref().unwrap_or("");
    let package = file.package.as_deref().unwrap_or("");

    // Collect messages that need TypeScript types
    // Only generate for messages with graphql.type or storage.entity options
    let mut interfaces = Vec::new();

    for proto_file in all_files {
        let proto_package = proto_file.package.as_deref().unwrap_or("");
        if proto_package != package {
            continue;
        }

        let proto_file_name = proto_file.name.as_deref().unwrap_or("");
        for message in &proto_file.message_type {
            let msg_name = message.name.as_deref().unwrap_or("");

            // Check if this message has graphql or entity options
            let has_graphql = get_cached_graphql_type_options(proto_file_name, msg_name).is_some();
            let has_entity = get_cached_entity_options(proto_file_name, msg_name).is_some();

            if has_graphql || has_entity {
                if let Some(interface) = generate_interface(proto_file_name, message)? {
                    interfaces.push(interface);
                }
            }
        }
    }

    if interfaces.is_empty() {
        return Ok(None);
    }

    // Build the output file
    let output_filename = format!("{}/typescript/types.d.ts", package.replace('.', "/"));

    let content = format!(
        r#"/**
 * TypeScript type definitions generated from protobuf messages
 *
 * @generated by protoc-gen-synapse
 * DO NOT EDIT MANUALLY
 */

// =============================================================================
// Utility Types
// =============================================================================

/** Nullable type for optional proto fields */
export type Nullable<T> = T | null | undefined;

// =============================================================================
// Message Types
// =============================================================================

{}
"#,
        interfaces.join("\n\n")
    );

    Ok(Some(File {
        name: Some(output_filename),
        content: Some(content),
        ..Default::default()
    }))
}

/// Generate a TypeScript interface from a proto message
fn generate_interface(
    file_name: &str,
    message: &DescriptorProto,
) -> Result<Option<String>, GeneratorError> {
    let msg_name = message.name.as_deref().unwrap_or("");

    // Generate fields
    let mut fields = Vec::new();
    for field in &message.field {
        if let Some(field_def) = generate_field(field)? {
            fields.push(field_def);
        }
    }

    // Check for resolver options to add virtual fields
    if let Some(resolver_opts) = get_cached_graphql_resolver_options(file_name, msg_name) {
        for virtual_field in &resolver_opts.fields {
            let field_name = virtual_field.name.to_lower_camel_case();
            let field_type = graphql_type_to_typescript(&virtual_field.r#type);
            let comment = virtual_field
                .description
                .as_ref()
                .map(|d| format!("  /** {} */\n", d))
                .unwrap_or_default();
            fields.push(format!("{}  {}: {};", comment, field_name, field_type));
        }
    }

    if fields.is_empty() {
        return Ok(None);
    }

    let interface = format!(
        r#"export interface {} {{
{}
}}"#,
        msg_name,
        fields.join("\n")
    );

    Ok(Some(interface))
}

/// Generate a TypeScript field definition from a proto field
fn generate_field(field: &FieldDescriptorProto) -> Result<Option<String>, GeneratorError> {
    let field_name = field.name.as_deref().unwrap_or("");
    let ts_name = field_name.to_lower_camel_case();

    // Get the TypeScript type
    let ts_type = proto_type_to_typescript(field);

    // Check if optional - in proto3, only fields with explicit 'optional' keyword
    // proto3_optional() returns true for fields marked with 'optional' keyword
    let is_optional = field.proto3_optional();
    let is_repeated = field.label() == Label::Repeated;

    // Message types are always nullable (can be unset)
    let is_message = field.r#type() == Type::Message;

    let full_type = if is_repeated {
        format!("{}[]", ts_type)
    } else if is_optional || is_message {
        format!("Nullable<{}>", ts_type)
    } else {
        ts_type
    };

    Ok(Some(format!("  {}: {};", ts_name, full_type)))
}

/// Convert a proto field type to TypeScript type
fn proto_type_to_typescript(field: &FieldDescriptorProto) -> String {
    match field.r#type() {
        Type::Double | Type::Float => "number".to_string(),
        Type::Int64 | Type::Uint64 | Type::Sint64 | Type::Fixed64 | Type::Sfixed64 => {
            "number".to_string() // BigInt would be more accurate but number is more convenient
        }
        Type::Int32 | Type::Uint32 | Type::Sint32 | Type::Fixed32 | Type::Sfixed32 => {
            "number".to_string()
        }
        Type::Bool => "boolean".to_string(),
        Type::String => "string".to_string(),
        Type::Bytes => "Uint8Array".to_string(),
        Type::Enum => {
            // Get enum type name
            field
                .type_name
                .as_ref()
                .map(|t| extract_type_name(t))
                .unwrap_or_else(|| "number".to_string())
        }
        Type::Message => {
            // Get message type name
            let type_name = field
                .type_name
                .as_ref()
                .map(|t| extract_type_name(t))
                .unwrap_or_else(|| "unknown".to_string());

            // Handle well-known types
            match type_name.as_str() {
                "Timestamp" => "string".to_string(), // ISO 8601 format
                "Duration" => "string".to_string(),
                "Any" => "unknown".to_string(),
                "Struct" => "Record<string, unknown>".to_string(),
                "Value" => "unknown".to_string(),
                "ListValue" => "unknown[]".to_string(),
                "BoolValue" | "StringValue" | "BytesValue" | "DoubleValue" | "FloatValue"
                | "Int32Value" | "Int64Value" | "UInt32Value" | "UInt64Value" => {
                    // Wrapper types - unwrap to the inner type, nullable
                    match type_name.as_str() {
                        "BoolValue" => "Nullable<boolean>".to_string(),
                        "StringValue" => "Nullable<string>".to_string(),
                        "BytesValue" => "Nullable<Uint8Array>".to_string(),
                        _ => "Nullable<number>".to_string(),
                    }
                }
                _ => type_name,
            }
        }
        Type::Group => "unknown".to_string(), // Deprecated
    }
}

/// Convert a GraphQL type string to TypeScript
fn graphql_type_to_typescript(graphql_type: &str) -> String {
    let trimmed = graphql_type.trim();

    // Check for non-null (!)
    let (base_type, is_required) = if trimmed.ends_with('!') {
        (&trimmed[..trimmed.len() - 1], true)
    } else {
        (trimmed, false)
    };

    // Check for list ([...])
    if base_type.starts_with('[') && base_type.ends_with(']') {
        let inner = &base_type[1..base_type.len() - 1];
        let inner_ts = graphql_type_to_typescript(inner);
        let array_type = format!("{}[]", inner_ts);
        if is_required {
            array_type
        } else {
            format!("Nullable<{}>", array_type)
        }
    } else {
        // Scalar type
        let ts_type = match base_type {
            "String" | "ID" => "string",
            "Int" | "Float" => "number",
            "Boolean" => "boolean",
            _ => base_type, // Custom type, use as-is
        };

        if is_required {
            ts_type.to_string()
        } else {
            format!("Nullable<{}>", ts_type)
        }
    }
}

/// Extract the type name from a fully-qualified proto type name
fn extract_type_name(type_name: &str) -> String {
    type_name
        .rsplit('.')
        .next()
        .unwrap_or(type_name)
        .to_string()
}
